// <auto-generated />
namespace YouthSailingClassifieds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Insert_Listing_Types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insert_Listing_Types));
        
        string IMigrationMetadata.Id
        {
            get { return "201506010117074_Insert_Listing_Types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
